language: node_js
sudo: false
node_js:
  - "stable"

script:
  - npm --version; node --version; yarn --version
  - yarn install --pure-lockfile
  - yarn workspaces run build
  - yarn workspaces run test